##################################
# Stack:                         #
# Backend: Springboot (Monolith) #
# Datbase: Postgres              #
# Frontend: Angular              #
# ################################

version: '3.7'
services:
  backend:
    image: agileboard-backend:springboot
    ports:
      - 9000:8080
    depends_on:
      - db
    networks:
      - agileboard
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: agileboard
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
    networks: 
      - agileboard
  frontend:
    image: agileboard-frontend:ng
    ports:
      - 88:80
    volumes:
      - ./frontend-ng/dist/agile-board-ui:/usr/share/nginx/html
    networks:
      - agileboard
    depends_on:
      - backend
volumes:
  psql:
networks:
  agileboard:
